export const validation = {

    MIN_FIRSTNAME_LENGTH: 1,
    MAX_FIRSTNAME_LENGTH: 30,
    MIN_LASTNAME_LENGTH: 1,
    MAX_LASTNAME_LENGTH: 30,
    MIN_USERNAME_LENGTH: 3,
    MAX_USERNAME_LENGTH: 30,
    MIN_EMAIL_LENGTH: 6,
    MAX_EMAIL_LENGTH: 32,
    MIN_PHONE_NUM_LENGTH: 10,
    MIN_PASSWORD_LENGTH: 8,
    MAX_PASSWORD_LENGTH: 30,
    MIN_TITLE_LENGTH: 3,
    MAX_TITLE_LENGTH: 30,
    MAX_ADDITIONAL_INFO_LENGTH: 500,

};

export const WEATHER_API_KEY = "9c8806d8db30401c82d205958232008"; // Gergana https://www.weatherapi.com
